import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "i18n for Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    children
  );
}
