import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import './globals.css';
import { inter } from '@/ui/font';
import Header from '@/components/header';
import Footer from '@/components/footer';
import type { Metadata } from "next";

// Can be imported from a shared config
const locales = ['en', 'es'];

export const metadata: Metadata = {
  title: "i18n for Next.js",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen max-w-4xl mx-auto'>
          <Header />
          <div className='flex-grow mt-20'>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}